kind = "web"
previewPath = "/"
title = "Project Kritagyata"
version = "1.0.0"
id = "artifacts/project-kritagyata"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20977

[services.development]
run = "pnpm --filter @workspace/project-kritagyata run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/project-kritagyata", "run", "build" ]
publicDir = "artifacts/project-kritagyata/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20977"
BASE_PATH = "/"
